from dataclasses import dataclass

@dataclass
class Monitor:
    """
    Monitor data model
    """
    ke: str
    name: str
    shto: list
    shfr: list
    type: str
    ext: str
    protocol: str
    host: str
    path: str
    port: int
    fps: int
    mode: str
    width: int
    height: int
    saveDir: str
    currentlyWatching: int
    status: str
    code: str
    streams: list
    streamsSortedByType: list

    @dataclass
    class details:
        max_keep_days: int
        notes: str
        dir: str
        auto_compress_videos: int
        rtmp_key: str
        auto_host_enable: int
        auto_host: str
        rtsp_transport: str
        muser: str
        mpass:str
        port_force: int
        fatal_max: int
        skip_ping: int
        is_onvif: int
        onvif_non_standard: str
        onvif_port: str
        primary_input: str
        aduration: str
        probesize: str
        stream_loop: str
        sfps: str
        wall_clock_timestamp_ignore: str
        accelerator: str
        hwaccel: str
        hwaccel_vcodec: str
        hwaccel_device: str
        stream_type: str
        stream_flv_type: str
        stream_flv_maxLatency: str
        stream_mjpeg_clients: str
        stream_vcodec: str
        stream_acodec: str
        hls_time: str
        hls_list_size: str
        preset_stream: str
        stream_quality: str
        stream_fps: str
        stream_scale_x: str
        stream_scale_y: str
        stream_rotate: str
        signal_check: str
        signal_check_log: str
        stream_vf: str
        tv_channel: str
        tv_channel_id: str
        tv_channel_group_title: str
        stream_timestamp: str
        stream_timestamp_font: str
        stream_timestamp_font_size: str
        stream_timestamp_color: str
        stream_timestamp_box_color: str
        stream_timestamp_x: str
        stream_timestamp_y: str
        stream_watermark: str
        stream_watermark_location: str
        stream_watermark_position: str
        snap: str
        snap_fps: str
        snap_scale_x: str
        snap_scale_y: str
        snap_vf: str
        vcodec: str
        crf: str
        preset_record: str
        acodec: str
        record_scale_y: str
        record_scale_x: str
        cutoff: str
        rotate: str
        vf: str
        timestamp: str
        timestamp_font: str
        timestamp_font_size: str
        timestamp_color: str
        timestamp_box_color: str
        timestamp_x: str
        timestamp_y: str
        watermark: str
        watermark_location: str
        watermark_position: str
        record_timelapse: str
        record_timelapse_mp4: str
        record_timelapse_fps: str
        record_timelapse_scale_x: str
        record_timelapse_scale_y: str
        record_timelapse_vf: str
        record_timelapse_watermark: str
        record_timelapse_watermark_location: str
        record_timelapse_watermark_position: str
        detector: str
        onvif_events: str
        detector_save: str
        use_detector_filters: str
        use_detector_filters_object: str
        detector_record_method: str
        detector_trigger: str
        detector_buffer_seconds_before: str
        detector_timeout: str
        watchdog_reset: str
        detector_delete_motionless_videos: str
        detector_http_api: str
        detector_send_frames: str
        detector_fps: str
        detector_scale_x: str
        detector_scale_y: str
        detector_lock_timeout: str
        detector_send_video_length: str
        snap_seconds_inward: str
        cords: str
        detector_filters: str
        det_multi_trig: str
        group_detector_multi: list
        detector_pam: str
        detector_sensitivity: str
        detector_max_sensitivity: str
        detector_threshold: str
        detector_color_threshold: str
        inverse_trigger: str
        detector_frame: str
        detector_motion_tile_mode: str
        detector_tile_size: str
        detector_noise_filter: str
        detector_noise_filter_range: str
        detector_use_detect_object: str
        detector_send_frames_object: str
        detector_obj_count_in_region: str
        detector_obj_region: str
        detector_use_motion: str
        detector_fps_object: str
        detector_scale_x_object: str
        detector_scale_y_object: str
        detector_buffer_vcodec: str
        detector_buffer_acodec: str
        detector_buffer_fps: str
        event_record_scale_x: str
        event_record_scale_y: str
        event_record_aduration: str
        event_record_probesize: str
        detector_audio: str
        detector_audio_min_db: str
        detector_audio_max_db: str
        detector_webhook: str
        detector_webhook_timeout: str
        detector_webhook_url: str
        detector_webhook_method: str
        detector_command_enable: str
        detector_command: str
        detector_command_timeout: str
        detector_notrigger: str
        detector_notrigger_timeout: str
        detector_notrigger_discord: str
        detector_notrigger_webhook: str
        detector_notrigger_webhook_url: str
        detector_notrigger_webhook_method: str
        detector_notrigger_command_enable: str
        detector_notrigger_command: str
        detector_notrigger_command_timeout: str
        control: str
        control_base_url: str
        control_url_method: str
        control_digest_auth: str
        control_stop: str
        control_url_stop_timeout: str
        control_turn_speed: str
        detector_ptz_follow: str
        detector_ptz_follow_target: str
        control_url_center: str
        control_url_left: str
        control_url_left_stop: str
        control_url_right: str
        control_url_right_stop: str
        control_url_up: str
        control_url_up_stop: str
        control_url_down: str
        control_url_down_stop: str
        control_url_enable_nv: str
        control_url_disable_nv: str
        control_url_zoom_out: str
        control_url_zoom_out_stop: str
        control_url_zoom_in: str
        control_url_zoom_in_stop: str
        control_invert_y: str
        groups: list
        notify_emailClient: str
        notify_global_webhook: str
        notify_onUnexpectedExit: str
        notify_useRawSnapshot: str
        detector_emailClient_timeout: str
        cust_input: str
        cust_stream: str
        cust_snap: str
        cust_record: str
        cust_detect: str
        cust_detect_object: str
        cust_sip_record: str
        custom_output: str
        loglevel: str
        sqllog: str
        detector_cascades: str
        stream_channels: str
        input_maps: str

        @dataclass
        class input_map_choices:
            stream: list
            snap: list
            record: list
            record_timelapse: list
            detector: list
            detector_object: list
            detector_sip_buffer: list

        @dataclass
        class substream:
            @dataclass
            class input:
                type: str
                stream_flv_type: str
                fulladdress: str
                sfps: str
                aduration: str
                probesize: str
                stream_loop: str
                rtsp_transport: str
                accelerator: str
                hwaccel: str
                hwaccel_vcodec: str
                hwaccel_device: str
                cust_input: str

            @dataclass
            class output:
                stream_type: str
                stream_mjpeg_clients: str
                stream_vcodec: str
                stream_acodec: str
                hls_time: str
                hls_list_size: str
                preset_stream: str
                stream_quality: str
                stream_v_br: str
                stream_a_br: str
                stream_fps: str
                stream_scale_x: str
                stream_scale_y: str
                stream_rotate: str
                svf: str
                cust_stream: str
